player(player).
expplayer(0).
expfarming(0).
expfishing(0).
expranching(0).
levelplayer(1).
levelfarming(1).
levelfishing(1).
levelranching(1).
nextlevelexp(100).
nextlevelexpfarming(100).
nextlevelexpfishing(100).
nextlevelexpranching(100).
locPlayer(8,13).
